### ISSUE TITLE
When Dragging Maximized from top left, Window bugs and shows rectangular shape and double window decoration

### ISSUE THREAD

**Issue by PMARZV** [amir1376/compose-custom-window-frame#4]
I love this btw! When trying to snap, the window doesnt resize to the recommended snap "shape and size". It like it returns to last last placement known

And secondly, when the window is fully maximized and you drag it from the top left, its like its stays maximized (rectangle shape) and the decoration top bar appears cut in the top and is usable.

[Video Url Example](https://streamable.com/g6qfwj)

Btw how can we create a distributable that works with JBR?? Currently, when creating it, it doesnt work like if there was no JBR

**Comment by amir1376** [comment]
>  It like it returns to last last placement known

You are right . That was produced from my previous commit which restores the last window placement because of this issue https://github.com/amir1376/compose-custom-window-frame/issues/2

now I fixed it here https://github.com/amir1376/compose-custom-window-frame/commit/a46c59eac7a6ecd8e2fe3cbf408c02ae7e9f5a0c

> Btw how can we create a distributable that works with JBR?? Currently, when creating it, it doesnt work like if there was no JBR

If you build your project with IDE's `Gradle Tool Window` you shouldn't face this problem as you set your project sdk to JBR

but if you are using terminal in that case you are using your JAVA_HOME as your jdk for your build (which may not pointed to the JBR)

To fix that.
Consider using [Gradle Toolchains](https://docs.gradle.org/current/userguide/toolchains.html)

Or just simply put this in your `app` build.gradle.kts file
```kotlin
kotlin {
    jvmToolchain {
        languageVersion=JavaLanguageVersion.of(17)
        //I think this vendor is added to gradle since 8.4
        vendor = JvmVendorSpec.Jetbrains
    }
}
```

**Comment by amir1376** [comment]
@PMARZV  Is your problem fixed?  

Can we close this issue?

**Comment by PMARZV** [comment]
Sorry for being late, the second part of the issue is still there. When maximized and dragging from the top left, the window decoration (a second one) appears cropped on top of the other and the windows stays rectangular. You can see the exact issue bu the end of the video above.

**Comment by amir1376** [comment]
Can you please give me the screenshot or a short video of the exact moment ?
I don't understand what is wrong actually!

**Comment by PMARZV** [comment]
Then we can close the issue (or we wait for the issue to resolve!)
